"""services price table + order_items.service_id

Revision ID: 8824c0db78cf
Revises: 50ac9ec03c5e
Create Date: 2026-06-13 07:57:32.089729+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8824c0db78cf'
down_revision: Union[str, None] = '50ac9ec03c5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('services',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('unit', sa.String(length=16), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=14, scale=0), server_default='0', nullable=False),
    sa.Column('pricing_type', sa.String(length=16), server_default='per_unit', nullable=False),
    sa.Column('display_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_services_tenant_active_order', 'services', ['tenant_id', 'is_active', 'display_order'], unique=False)
    op.create_table('service_tiers',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('service_id', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(length=64), nullable=False),
    sa.Column('max_value', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('price', sa.Numeric(precision=14, scale=0), nullable=False),
    sa.Column('per_unit', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('display_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_service_tiers_service_id', 'service_tiers', ['service_id'], unique=False)
    op.add_column('order_items', sa.Column('service_id', sa.UUID(), nullable=True))
    op.create_foreign_key(
        'fk_order_items_service_id', 'order_items', 'services', ['service_id'], ['id']
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_order_items_service_id', 'order_items', type_='foreignkey')
    op.drop_column('order_items', 'service_id')
    op.drop_index('ix_service_tiers_service_id', table_name='service_tiers')
    op.drop_table('service_tiers')
    op.drop_index('ix_services_tenant_active_order', table_name='services')
    op.drop_table('services')
    # ### end Alembic commands ###
